questions = [
    {'question': 'Is Python a dynamically typed language?', 'answer': True},
    {'question': 'Can lists contain elements of different data types?', 'answer': True},
    {'question': 'Does Python have a built-in support for regular expressions?', 'answer': True},
    {'question': 'Can Python be used to create desktop applications?', 'answer': True},
    {'question': 'Is the "print" function used to display output in Python?', 'answer': True},
    {'question': 'Is it possible to convert a string to a numeric type in Python?', 'answer': True},
    {'question': 'Are Python functions first-class objects?', 'answer': True},
    {'question': 'Does Python have a built-in support for multi-threading?', 'answer': True},
    {'question': 'Can tuples be used as keys in Python dictionaries?', 'answer': True},
    {'question': 'Is operator overloading supported in Python?', 'answer': True},
    {'question': 'Does Python have an equivalent of the switch statement in other languages?', 'answer': False},
    {'question': 'Can Python be used to create mobile applications?', 'answer': True},
    {'question': 'Is the division operator "/" used for integer division in Python?', 'answer': False},
    {'question': 'Do all objects in Python have a type?', 'answer': True},
    {'question': 'Does Python have a built-in support for date and time handling?', 'answer': True},
    {'question': 'Is it possible to define a class inside another class in Python?', 'answer': True},
    {'question': 'Can the "range" function be used to create an infinite loop?', 'answer': False},
    {'question': 'Is Python case-sensitive?', 'answer': True},
    {'question': 'Can Python code be compiled into machine code?', 'answer': True},
    {'question': 'Does Python have a built-in support for serialization?', 'answer': True},
]